## Fichier de config pour le deploiement de l'application sur le VPS
## Pour deploiement dans un environnement donne (Staging ou prod), modifier le port ainsi que le container_name et c'est correct

services:
  backend:
    image: ${NEXUS_REGISTRY}/${IMAGE_PREFIX}-backend:${IMAGE_TAG:-latest}
    container_name: vireel-prod-backend
    ports:
      - "5000:8000"
    volumes:
      - output-data:/app/output
      - /var/apps/secrets/cookies.txt:/app/cookies.txt
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - prod-network

  frontend:
    image: ${NEXUS_REGISTRY}/${IMAGE_PREFIX}-frontend:${IMAGE_TAG:-latest}
    container_name: vireel-prod-frontend
    ports:
      - "5001:5173"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - prod-network

  renderer:
    image: ${NEXUS_REGISTRY}/${IMAGE_PREFIX}-renderer:${IMAGE_TAG:-latest}
    container_name: vireel-prod-renderer
    ports:
      - "5002:3100"
    volumes:
      - output-data:/output
    environment:
      - REMOTION_BUNDLE_PATH=/app/remotion
      - OUTPUT_DIR=/output
      - PORT=3100
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - prod-network

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: vireel-prod-pot-provider
    restart: unless-stopped
    networks:
      - prod-network

volumes:
  output-data:

networks:
  prod-network:
    driver: bridge