import emojilib from "emojilib";

// 1. Nettoyer et réduire le mot à sa forme racine (Français / Anglais basique)
export function normalizeWord(word: string): string {
    return word
        .toLowerCase()
        .trim()
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "") // Supprime les accents (ex: "brûlant" -> "brulant")
        .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"'…]/g, "") // Supprime la ponctuation
        .replace(/(s|x|es|e)$/gi, ""); // Supprime les marques du pluriel / féminin simples
}

// Dictionnaire personnalisé prioritaire (pour vos mots sur-mesure / français)
const CUSTOM_OVERRIDE_MAP: Record<string, string> = {
    argent: "💸",
    milliard: "💰",
    fumee: "💨",
    vitesse: "⚡",
    astuce: "💡",
    idee: "💡",
    incroyable: "🤯",
    choquant: "😱",
    brulant: "🔥",
    lancement: "🚀",
    fire: "🔥",
    feu: "🔥",
    chaud: "🔥",
    boom: "💥",
    explosion: "💥",
    wow: "🤯",
    insane: "🤯",
    money: "💸",
    cash: "💸",
    profit: "💸",
    riche: "💸",
    million: "💰",
    amour: "❤️",
    love: "❤️",
    coeur: "❤️",
    merci: "🙏",
    bravo: "👏",
    funny: "😂",
    lol: "😂",
    mdr: "😂",
    haha: "😂",
    blague: "🤣",
    victoire: "🏆",
    succes: "🏆",
    win: "🏆",
    champion: "🏆",
    objectif: "🎯",
    danger: "⚠️",
    attention: "⚠️",
    alerte: "🚨",
    stop: "🛑",
    erreur: "❌",
    go: "🚀",
    letsgo: "🚀",
    rapide: "⚡",
    speed: "⚡",
    tip: "💡",
    secret: "🤫",
    bonus: "🎁",
    nouveau: "✨",
    nouveaute: "✨",
    parfait: "👌",
    ok: "👌",
    musique: "🎵",
    dance: "🕺",
    faim: "🍔",
    pizza: "🍕",
    cafe: "☕",
    vol: "✈️",
    vols: "✈️",
    flight: "✈️",
    accord: "🤝",
    handshake: "🤝",
    bienvenue: "👋",
    hello: "👋",
    salut: "👋",
    bye: "👋",
    aurevoir: "👋",
    chat: "🐱",
    chien: "🐶",
    animal: "🐾",
    animaux: "🐾",
    nature: "🌿",
    plante: "🌿",
    jardin: "🌿",
    soleil: "☀️",
    lune: "🌙",
    etoile: "⭐",
    stars: "⭐",
    ciel: "☁️",
    nuage: "☁️",
    pluie: "🌧️",
    neige: "❄️",
    vent: "💨",
    tempete: "🌪️",
    arcenciel: "🌈",
    rainbow: "🌈",
    feuillage: "🍂",
    automne: "🍁",
    hiver: "⛄",
    ete: "🏖️",
    printemps: "🌸",
    voyage: "🧳",
    vacances: "🏝️",
    plage: "🏖️",
    montagne: "🏔️",
    ville: "🏙️",
    maison: "🏠",
    appartement: "🏢",
    voiture: "🚗",
    velo: "🚲",
    moto: "🏍️",
    train: "🚆",
    bateau: "⛴️",
    mer: "🌊",
    ocean: "🌊",
    lac: "🏞️",
    riviere: "🏞️",
    foret: "🌲",
    jungle: "🌴",
    desert: "🏜️",
    volcan: "🌋",
    canyon: "🗻",
    ile: "🏝️",
    archipel: "🏝️",
    pont: "🌉",
    tunnel: "🚇",
    route: "🛣️",
    autoroute: "🛣️",
    station: "🏪",
    magasin: "🏬",
    restaurant: "🍽️",
    bar: "🍸",
    club: "🎶",
    cinema: "🎬",
    theatre: "🎭",
    concert: "🎤",
    festival: "🎪",
    sport: "🏅",
    football: "⚽",
    basketball: "🏀",
    tennis: "🎾",
    golf: "⛳",
    ski: "⛷️",
    surf: "🏄‍♂️",
    yoga: "🧘‍♀️",
    meditation: "🧘‍♂️",
    lecture: "📚",
    livre: "📖",
    ecriture: "✍️",
    peinture: "🎨",
    chant: "🎤",
    danse: "💃",
    aventure: "🗺️",
    exploration: "🧭",
    decouverte: "🔍",
    technologie: "💻",
    informatique: "🖥️",
    robotique: "🤖",
    intelligence: "🧠",
    science: "🔬",
    chimie: "⚗️",
    physique: "🧲",
    biologie: "🧬",
    espace: "🌌",
    astronomie: "🔭",
    planete: "🪐",
    galaxie: "🌌",
    univers: "🌌",
    matin: "☀️",
    midi: "☀️",
    morning: "☀️",
    soir: "🌑",
    night: "🌑",
    gare: "🚉",
    aeroport: "🛫",
    metro: "🚉",
    hotel: "🏨",
    chambre: "🛏️",
    piscine: "🏊‍♂️",
    spa: "💆‍♀️",
    massage: "💆‍♂️",
    shopping: "🛍️",
    boutique: "🛒",
    cadeau: "🎁",
    anniversaire: "🎂",
    fete: "🎉",
    mariage: "💍",
    couple: "👩‍❤️‍👨",
    famille: "👨‍👩‍👧‍👦",
    amis: "👯‍♂️",
    photographie: "📸",
    nourriture: "🍔",
    boisson: "🍹",
    passager: "🚶",
    passagers: "🚶🏽",
    passagere: "🚶🏽‍♀️",
    passageres: "🚶🏽‍♀️",
    heure: "🕐",
    heures: "🕐",
    temps: "🕐",
    malade: "😷",
    maladie: "😷",
    sante: "🩺",
    medecin: "👨‍⚕️",
    infirmier: "👩‍⚕️",
    hopital: "🏥",
    pharmacie: "💊",
    medicament: "💊",
    virus: "🦠",
    bacterie: "🦠",
    vaccin: "💉",
    injection: "💉",
    chirurgie: "🔪",
    operation: "🔪",
    dentiste: "🦷",
    dentifrice: "🪥",
    brosseadents: "🪥",
    lunettes: "👓",
    lunettesdesoleil: "🕶️",
    chapeau: "🎩",
    casquette: "🧢",
    bonnet: "🧢",
    echarpe: "🧣",
    gants: "🧤",
    chaussures: "👟",
    bottes: "🥾",
    robe: "👗",
    pantalon: "👖",
    chemise: "👕",
    pull: "🧥",
    manteau: "🧥",
    veste: "🧥",
    ceinture: "👖",
    sac: "👜",
};

// Map de recherche rapide O(1)
const EMOJI_SEARCH_INDEX = new Map<string, string>();

function initializeEmojiIndex() {
    if (EMOJI_SEARCH_INDEX.size > 0) return; // Déjà initialisé

    // A. Charger la bibliothèque emojilib (mots-clés)
    for (const [emoji, keywords] of Object.entries(emojilib)) {
        for (const keyword of keywords) {
            const cleanKeyword = normalizeWord(keyword);
            if (cleanKeyword && !EMOJI_SEARCH_INDEX.has(cleanKeyword)) {
                EMOJI_SEARCH_INDEX.set(cleanKeyword, emoji);
            }
        }
    }

    // B. Injecter vos mots personnalisés (ils écrasent emojilib si conflit)
    for (const [word, emoji] of Object.entries(CUSTOM_OVERRIDE_MAP)) {
        EMOJI_SEARCH_INDEX.set(normalizeWord(word), emoji);
    }
}

// Initialisation immédiate
initializeEmojiIndex();

/**
 * Fonction principale à appeler dans votre composant
 */
export const getEmojiForWord = (rawWord: string): string | null => {
    if (!rawWord) return null;

    const clean = normalizeWord(rawWord);
    if (clean.length <= 2) return null; // Ignorer les mots trop courts ("le", "un", "de", "it")

    return EMOJI_SEARCH_INDEX.get(clean) ?? null;
};