import {
    Home,
    Image,
    LayoutGrid,
    Settings,
} from "lucide-react";

export const DASHBOARD_SIDEBAR_ITEMS = [
    {
        key: "dashboard",
        title: "Dashboard",
        sidebarLabel: "Dashboard",
        icon: Home,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Hub principal pour acceder a tous les outils OpenShorts et a ton espace de production.",
        badge: "Hub",
        category: "hub",
        path: "/dashboard",
    },
    {
        key: "reels",
        title: "Reels generes",
        sidebarLabel: "Reels",
        icon: LayoutGrid,
        activeClassName: "bg-violet-500/10 text-violet-400",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Retrouve, filtre, partage et telecharge tous les reels generes.",
        badge: "Gallery",
        category: "service",
        path: "/dashboard/reels",
    },
    {
        key: "youtube-studio",
        title: "IA Captions",
        sidebarLabel: "IA Captions",
        icon: Image,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Galerie des videos avec captions IA adaptees par plateforme (TikTok, YouTube, LinkedIn, Facebook).",
        badge: "Gallery",
        category: "service",
        path: "/dashboard/youtube-resumes",
    },
    {
        key: "settings",
        title: "Settings",
        sidebarLabel: "Settings",
        icon: Settings,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Configure les cles Gemini, Upload-Post, ElevenLabs et fal.ai pour activer chaque service.",
        badge: "Config",
        category: "utility",
        path: "/dashboard/settings",
    },
];