import {
    CreditCardIcon,
    Home,
    Image,
    LayoutGrid,
    Settings,
} from "lucide-react";

export const DASHBOARD_SIDEBAR_ITEMS = [
    {
        key: "dashboard",
        title: "Dashboard",
        sidebarLabel: "Dashboard",
        icon: Home,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Hub principal pour acceder a tous les outils Vireel et a ton espace de production.",
        badge: "Hub",
        category: "hub",
        path: "/dashboard",
    },
    {
        key: "reels",
        title: "Reels generes",
        sidebarLabel: "Reels",
        icon: LayoutGrid,
        activeClassName: "bg-violet-500/10 text-violet-400",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Upload une video et laisse le systeme boosté à l'IA extraire les moments réels.",
        badge: "Gallery",
        category: "service",
        path: "/dashboard/reels",
    },
    {
        key: "caption-generator",
        title: "IA Captions",
        sidebarLabel: "IA Captions",
        icon: Image,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Upload une video, choisis la plateforme cible, ajuste les captions puis rends la version finale.",
        badge: "Gallery",
        category: "service",
        path: "/dashboard/captions",
    },
    {
        key: "abonnements",
        title: "Abonnements",
        sidebarLabel: "Abonnements",
        icon: CreditCardIcon,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Choisis la formule qui te conviens, et active les services que tu souhaites utiliser.",
        badge: "Config",
        category: "utility",
        path: "/dashboard/abonnements",
    },
    {
        key: "settings",
        title: "Settings",
        sidebarLabel: "Settings",
        icon: Settings,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Configure et adminsitre tes préférences",
        badge: "Config",
        category: "utility",
        path: "/dashboard/settings",
    },
];