import {
    Bot,
    Film,
    Home,
    Image,
    LayoutGrid,
    Settings,
    Sparkles,
} from "lucide-react";

export const DASHBOARD_SIDEBAR_ITEMS = [
    {
        key: "dashboard",
        title: "Dashboard",
        sidebarLabel: "Dashboard",
        icon: Home,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Hub principal pour acceder a tous les outils OpenShorts et a ton espace de production.",
        badge: "Hub",
        category: "hub",
        path: "/dashboard",
    },
    {
        key: "clip-generator",
        title: "Clip Generator",
        sidebarLabel: "Clip Generator",
        icon: Film,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Genere des shorts viraux a partir de videos longues avec l'analyse IA et le split view de production.",
        badge: "Core",
        category: "service",
        path: "/dashboard/clip-generator",
    },
    {
        key: "ai-shorts",
        title: "AI Shorts",
        sidebarLabel: "AI Shorts",
        icon: Sparkles,
        activeClassName: "bg-violet-500/10 text-violet-400",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Cree des videos courtes pour produits SaaS avec hooks, scripts et rendus automatises.",
        badge: "New",
        category: "service",
        path: "/dashboard/ai-shorts",
    },
    {
        key: "ai-agent",
        title: "AI Agent",
        sidebarLabel: "AI Agent",
        icon: Bot,
        activeClassName: "bg-emerald-500/10 text-emerald-400",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Pilote le workflow autonome de clipping pour traiter un lot de videos verticales.",
        badge: "Auto",
        category: "service",
        path: "/dashboard/ai-agent",
    },
    {
        key: "ugc-gallery",
        title: "UGC Gallery",
        sidebarLabel: "UGC Gallery",
        icon: LayoutGrid,
        activeClassName: "bg-violet-500/10 text-violet-400",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Parcours la galerie UGC et les variations creatives generees pour tes campagnes.",
        badge: "Gallery",
        category: "service",
        path: "/dashboard/ugc-gallery",
    },
    {
        key: "youtube-studio",
        title: "YouTube Studio",
        sidebarLabel: "YouTube Studio",
        icon: Image,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Genere des thumbnails et assets YouTube adaptes a tes clips et contenus longs.",
        badge: "Studio",
        category: "service",
        path: "/dashboard/youtube-studio",
    },
    {
        key: "settings",
        title: "Settings",
        sidebarLabel: "Settings",
        icon: Settings,
        activeClassName: "bg-primary/10 text-primary",
        inactiveClassName: "text-zinc-400 hover:text-white hover:bg-white/5",
        description: "Configure les cles Gemini, Upload-Post, ElevenLabs et fal.ai pour activer chaque service.",
        badge: "Config",
        category: "utility",
        path: "/dashboard/settings",
    },
];